# Services used for development

version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
