name: Payment cronjob

on:
  workflow_dispatch:
  schedule:
    # Run every 30 seconds
    - cron: "*/30 * * * *"

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: run payment check cron
        run: |
          cron_result=$(curl -o /dev/null -s -w "%{http_code}\n" https://satsbet-14prd3iag-wladpaiva.vercel.app/api/cron/payment)

          if [ "$cron_result" -ne 200 ]; then
              echo "Cron job failed with status code $cron_result"
              exit 1
          fi
